apiVersion: v1
kind: Service
metadata:
  name: tts-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tts-backend
  ports:
    - name: http
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
