{{- if .Values.audiobooks.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tts-lab.fullname" . }}-audiobooks
  labels:
    {{- include "tts-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.audiobooks.storage.persistence.size | quote }}
  {{- if .Values.audiobooks.storage.persistence.storageClassName }}
  storageClassName: {{ .Values.audiobooks.storage.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
