CREATE TABLE token_login_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_jti VARCHAR(255) NOT NULL,
    token_name VARCHAR(255) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_token_login_usage_jti ON token_login_usage (token_jti);
