CREATE TABLE prompt_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    user_email VARCHAR(320),
    model_type VARCHAR(32) NOT NULL,
    provider_model_name VARCHAR(255),
    prompt_text TEXT NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_prompt_history_user_created
    ON prompt_history (user_id, created_at DESC);

CREATE INDEX idx_prompt_history_user_model_created
    ON prompt_history (user_id, model_type, created_at DESC);
