/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/request-limits/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRequestLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPromptHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudiobooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAudiobookDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAudiobookTitle"];
        trace?: never;
    };
    "/api/audiobooks/{id}/audio-assets/{assetId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadAudioAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/{id}/audio-assets/{assetId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamAudioAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVoiceCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/speaker-voice-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyzeSpeakerVoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/speaker-split-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["splitDialogue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/emotion-annotation-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["annotateEmotions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/script-preview-save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveScriptPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/final-request-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buildFinalRequestPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/single-speaker-render-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buildSingleSpeakerRenderPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/create-audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}/audio-generated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeAudiobookAudioGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAudiobookWorkflowSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}/cast-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveAudiobookCast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}/cast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAudiobookWorkflowCast"];
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}/script-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveAudiobookScript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audiobooks/workflow/projects/{projectId}/production-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAudiobookWorkflowProductionSettings"];
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        ApiErrorResponse: {
            /** Format: int32 */
            status: number;
            code: string;
            message: string;
            details?: string | null;
            requestId: string;
        };
        CurrentUser: {
            id: string;
            email: string;
            name: string;
            roles: string[];
            authMode: components["schemas"]["AuthMode"];
        };
        /** @enum {string} */
        AuthMode: "google" | "mock";
        /** @enum {string} */
        ModelType: "TEXT_MODEL" | "SPEECH_MODEL";
        /** @enum {string} */
        PromptRequestStatus: "SUCCESS" | "FAILED" | "RATE_LIMITED";
        /** @enum {string} */
        RequestRateLimitUnit: "WORDS" | "TOKENS";
        RequestRateLimitSummary: {
            /** Format: date-time */
            windowResetAt: string;
            /** Format: int64 */
            windowSeconds: number;
            limits: components["schemas"]["RequestRateLimitSummaryItem"][];
        };
        RequestRateLimitSummaryItem: {
            modelType: components["schemas"]["ModelType"];
            /** Format: int64 */
            used: number;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            remaining: number;
            unit: components["schemas"]["RequestRateLimitUnit"];
        };
        PromptHistoryResponse: {
            items: components["schemas"]["PromptHistoryItem"][];
        };
        PromptHistoryItem: {
            /** Format: int64 */
            id: number;
            userId: string;
            userEmail: string | null;
            modelType: components["schemas"]["ModelType"];
            providerModelName: string | null;
            promptText: string;
            requestStatus: components["schemas"]["PromptRequestStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        AudioAssetType: "SPEECH_SEGMENT_MP3" | "CHAPTER_MP3" | "FULL_AUDIOBOOK" | "PREVIEW_MP3" | "EXPORT_ZIP";
        /** @enum {string} */
        AudioAssetStatus: "GENERATING" | "READY" | "FAILED";
        /** @enum {string} */
        AudiobookProjectStatus: "DRAFT" | "GENERATING" | "NEEDS_REVIEW" | "APPROVED" | "EXPORTED" | "FAILED";
        /** @enum {string} */
        AudiobookSpeechSegmentReviewStatus: "PENDING" | "NEEDS_CHANGES" | "APPROVED";
        AudioAssetResponse: {
            id: string;
            speechSegmentId: string | null;
            type: components["schemas"]["AudioAssetType"];
            /** Format: int32 */
            version: number;
            filename: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: int32 */
            durationSeconds: number | null;
            status: components["schemas"]["AudioAssetStatus"];
            /** Format: date-time */
            createdAt: string;
            downloadUrl: string;
            streamUrl: string;
            speakerName?: string | null;
        };
        AudiobookSummaryResponse: {
            items: components["schemas"]["AudiobookSummary"][];
        };
        AudiobookSummary: {
            id: string;
            title: string;
            status: components["schemas"]["AudiobookProjectStatus"];
            /** Format: int32 */
            speechSegmentCount: number;
            /** Format: int32 */
            speakerCount: number | null;
            /** Format: int32 */
            totalDurationSeconds: number | null;
            /** Format: date-time */
            updatedAt: string;
            audioAssets: components["schemas"]["AudioAssetResponse"][];
        };
        AudiobookSpeechSegmentResponse: {
            id: string;
            /** Format: int32 */
            orderIndex: number;
            title: string;
            reviewStatus: components["schemas"]["AudiobookSpeechSegmentReviewStatus"];
            /** Format: int32 */
            durationSeconds: number | null;
            speakerName: string | null;
            speakerRoleDescription: string | null;
            voiceName: string | null;
            performanceDirections: string | null;
        };
        AudiobookDetailResponse: {
            id: string;
            title: string;
            status: components["schemas"]["AudiobookProjectStatus"];
            /** Format: int32 */
            speechSegmentCount: number;
            /** Format: int32 */
            speakerCount: number | null;
            /** Format: int32 */
            totalDurationSeconds: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            speechSegments: components["schemas"]["AudiobookSpeechSegmentResponse"][];
            audioAssets: components["schemas"]["AudioAssetResponse"][];
        };
        /** @enum {string} */
        AudiobookWorkflowStage: "CAST_REVIEW" | "CAST_APPROVED" | "SCRIPT_REVIEW" | "SCRIPT_APPROVED" | "PERFORMANCE_READY" | "AUDIO_GENERATED";
        AudiobookWorkflowProductionSettings: {
            prompt: string;
            languageCode: string;
            modelName: string;
            audioEncoding: string;
        };
        AudiobookWorkflowProductionSettingsRequest: {
            prompt: string;
            languageCode: string;
            modelName: string;
            audioEncoding: string;
        };
        AudiobookWorkflowSnapshotResponse: {
            projectId: string;
            title: string;
            storyText?: string | null;
            sourceLanguageCode: string;
            workflowStage: components["schemas"]["AudiobookWorkflowStage"];
            speakers: components["schemas"]["SpeakerVoiceAnalysisItem"][];
            scriptTurns: components["schemas"]["SpeakerSplitTurn"][];
            annotatedTurns: components["schemas"]["AnnotatedSpeakerTurn"][];
            productionSettings: components["schemas"]["AudiobookWorkflowProductionSettings"];
            audioAssets: components["schemas"]["AudioAssetResponse"][];
            audioAssetsCurrent: boolean;
            performanceNotesStale: boolean;
            mergedAudioUrl?: string | null;
        };
        AudiobookWorkflowCastUpdateRequest: {
            speakers: components["schemas"]["SpeakerVoiceAnalysisItem"][];
        };
        ChatRequest: {
            message: string;
            conversationId?: string | null;
        };
        ChatResponse: {
            answer: string;
            conversationId: string;
        };
        SpeakerVoiceAnalysisItem: {
            speakerName: string;
            roleDescription: string;
            voiceSuggestion: string;
        };
        SpeakerVoiceAnalysisRequest: {
            rawDialogue: string;
        };
        SpeakerVoiceAnalysisResponse: {
            speakers: components["schemas"]["SpeakerVoiceAnalysisItem"][];
            projectId: string | null;
            projectTitle: string;
            sourceLanguageCode: string;
            productionLanguageCode: string;
        };
        SpeakerSplitTurn: {
            speaker: string;
            text: string;
        };
        SpeakerSplitAnalysisRequest: {
            rawDialogue: string;
            speakers: components["schemas"]["SpeakerVoiceAnalysisItem"][];
            projectId: string;
        };
        SpeakerSplitAnalysisResponse: {
            turns: components["schemas"]["SpeakerSplitTurn"][];
        };
        AnnotatedSpeakerTurn: {
            speaker: string;
            text: string;
        };
        EmotionAnnotationAnalysisRequest: {
            projectId: string;
        };
        EmotionAnnotationAnalysisResponse: {
            turns: components["schemas"]["AnnotatedSpeakerTurn"][];
        };
        ScriptPreviewSaveRequest: {
            projectId: string;
            turns: components["schemas"]["SpeakerSplitTurn"][];
        };
        UpdateAudiobookTitleRequest: {
            title: string;
        };
        FinalTtsRequestPreviewRequest: {
            prompt: string;
            speakers: components["schemas"]["SpeakerVoiceAnalysisItem"][];
            annotatedTurns: components["schemas"]["AnnotatedSpeakerTurn"][];
            languageCode: string;
            modelName: string;
            audioEncoding: string;
        };
        FinalTtsRequestPreviewResponse: {
            input: {
                [key: string]: unknown;
            };
            voice: {
                [key: string]: unknown;
            };
            audioConfig: {
                [key: string]: unknown;
            };
        };
        SingleSpeakerRenderPlanRequest: {
            input: {
                [key: string]: unknown;
            };
            voice: {
                [key: string]: unknown;
            };
            audioConfig: {
                [key: string]: unknown;
            };
        };
        SingleSpeakerRenderRequest: {
            input: {
                [key: string]: unknown;
            };
            voice: {
                [key: string]: unknown;
            };
            audioConfig: {
                [key: string]: unknown;
            };
        };
        CreateAudioRequest: {
            /** @description ID of the project containing segments to render */
            projectId: string;
            /** @description Zero-based index of the speech segment to render */
            targetSegmentIndex: number;
        };
        SingleSpeakerRenderPlanResponse: {
            renderRequests: components["schemas"]["SingleSpeakerRenderRequest"][];
        };
        SpeakerVoiceCatalogItem: {
            id: string;
            providerVoiceName: string;
            displayName: string;
            description: string;
            imageUrl: string;
            demoMp3Url: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
        };
    };
    responses: {
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description Rate limited */
        RateLimitedError: {
            headers: {
                "X-Request-Id"?: string;
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description Provider unavailable */
        ProviderUnavailableError: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description Unexpected internal failure */
        InternalError: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type ApiErrorResponse = components['schemas']['ApiErrorResponse'];
export type CurrentUser = components['schemas']['CurrentUser'];
export type AuthMode = components['schemas']['AuthMode'];
export type ModelType = components['schemas']['ModelType'];
export type PromptRequestStatus = components['schemas']['PromptRequestStatus'];
export type RequestRateLimitUnit = components['schemas']['RequestRateLimitUnit'];
export type RequestRateLimitSummary = components['schemas']['RequestRateLimitSummary'];
export type RequestRateLimitSummaryItem = components['schemas']['RequestRateLimitSummaryItem'];
export type PromptHistoryResponse = components['schemas']['PromptHistoryResponse'];
export type PromptHistoryItem = components['schemas']['PromptHistoryItem'];
export type AudioAssetType = components['schemas']['AudioAssetType'];
export type AudioAssetStatus = components['schemas']['AudioAssetStatus'];
export type AudiobookProjectStatus = components['schemas']['AudiobookProjectStatus'];
export type AudiobookSpeechSegmentReviewStatus = components['schemas']['AudiobookSpeechSegmentReviewStatus'];
export type AudioAssetResponse = components['schemas']['AudioAssetResponse'];
export type AudiobookSummaryResponse = components['schemas']['AudiobookSummaryResponse'];
export type AudiobookSummary = components['schemas']['AudiobookSummary'];
export type AudiobookSpeechSegmentResponse = components['schemas']['AudiobookSpeechSegmentResponse'];
export type AudiobookDetailResponse = components['schemas']['AudiobookDetailResponse'];
export type AudiobookWorkflowStage = components['schemas']['AudiobookWorkflowStage'];
export type AudiobookWorkflowProductionSettings = components['schemas']['AudiobookWorkflowProductionSettings'];
export type AudiobookWorkflowProductionSettingsRequest = components['schemas']['AudiobookWorkflowProductionSettingsRequest'];
export type AudiobookWorkflowSnapshotResponse = components['schemas']['AudiobookWorkflowSnapshotResponse'];
export type AudiobookWorkflowCastUpdateRequest = components['schemas']['AudiobookWorkflowCastUpdateRequest'];
export type ChatRequest = components['schemas']['ChatRequest'];
export type ChatResponse = components['schemas']['ChatResponse'];
export type SpeakerVoiceAnalysisItem = components['schemas']['SpeakerVoiceAnalysisItem'];
export type SpeakerVoiceAnalysisRequest = components['schemas']['SpeakerVoiceAnalysisRequest'];
export type SpeakerVoiceAnalysisResponse = components['schemas']['SpeakerVoiceAnalysisResponse'];
export type SpeakerSplitTurn = components['schemas']['SpeakerSplitTurn'];
export type SpeakerSplitAnalysisRequest = components['schemas']['SpeakerSplitAnalysisRequest'];
export type SpeakerSplitAnalysisResponse = components['schemas']['SpeakerSplitAnalysisResponse'];
export type AnnotatedSpeakerTurn = components['schemas']['AnnotatedSpeakerTurn'];
export type EmotionAnnotationAnalysisRequest = components['schemas']['EmotionAnnotationAnalysisRequest'];
export type EmotionAnnotationAnalysisResponse = components['schemas']['EmotionAnnotationAnalysisResponse'];
export type ScriptPreviewSaveRequest = components['schemas']['ScriptPreviewSaveRequest'];
export type UpdateAudiobookTitleRequest = components['schemas']['UpdateAudiobookTitleRequest'];
export type FinalTtsRequestPreviewRequest = components['schemas']['FinalTtsRequestPreviewRequest'];
export type FinalTtsRequestPreviewResponse = components['schemas']['FinalTtsRequestPreviewResponse'];
export type SingleSpeakerRenderPlanRequest = components['schemas']['SingleSpeakerRenderPlanRequest'];
export type SingleSpeakerRenderRequest = components['schemas']['SingleSpeakerRenderRequest'];
export type CreateAudioRequest = components['schemas']['CreateAudioRequest'];
export type SingleSpeakerRenderPlanResponse = components['schemas']['SingleSpeakerRenderPlanResponse'];
export type SpeakerVoiceCatalogItem = components['schemas']['SpeakerVoiceCatalogItem'];
export type ResponseValidationError = components['responses']['ValidationError'];
export type ResponseRateLimitedError = components['responses']['RateLimitedError'];
export type ResponseProviderUnavailableError = components['responses']['ProviderUnavailableError'];
export type ResponseNotFoundError = components['responses']['NotFoundError'];
export type ResponseInternalError = components['responses']['InternalError'];
export type ResponseUnauthorizedError = components['responses']['UnauthorizedError'];
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getRequestLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current request usage summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRateLimitSummary"];
                };
            };
        };
    };
    getPromptHistory: {
        parameters: {
            query?: {
                modelType?: components["schemas"]["ModelType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt history for the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptHistoryResponse"];
                };
            };
        };
    };
    listAudiobooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audiobooks owned by the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookSummaryResponse"];
                };
            };
        };
    };
    getAudiobookDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audiobook detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookDetailResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    updateAudiobookTitle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAudiobookTitleRequest"];
            };
        };
        responses: {
            /** @description Updated audiobook detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookDetailResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    downloadAudioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloadable audio asset */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
        };
    };
    streamAudioAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streamable audio asset */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Chat completion response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimitedError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["ProviderUnavailableError"];
        };
    };
    getVoiceCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All available speaker voices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerVoiceCatalogItem"][];
                };
            };
        };
    };
    analyzeSpeakerVoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerVoiceAnalysisRequest"];
            };
        };
        responses: {
            /** @description Speaker voice analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerVoiceAnalysisResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimitedError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["ProviderUnavailableError"];
        };
    };
    splitDialogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerSplitAnalysisRequest"];
            };
        };
        responses: {
            /** @description Speaker split analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerSplitAnalysisResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimitedError"];
            500: components["responses"]["InternalError"];
        };
    };
    annotateEmotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmotionAnnotationAnalysisRequest"];
            };
        };
        responses: {
            /** @description Emotion annotation analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    saveScriptPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptPreviewSaveRequest"];
            };
        };
        responses: {
            /** @description Persisted script preview turns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerSplitAnalysisResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    buildFinalRequestPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalTtsRequestPreviewRequest"];
            };
        };
        responses: {
            /** @description Final TTS request preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalTtsRequestPreviewResponse"];
                };
            };
        };
    };
    buildSingleSpeakerRenderPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SingleSpeakerRenderPlanRequest"];
            };
        };
        responses: {
            /** @description Single-speaker render plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleSpeakerRenderPlanResponse"];
                };
            };
        };
    };
    createAudio: {
        parameters: {
            query: {
                projectId: string;
                targetSegmentIndex: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered audio download */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    "X-Audiobook-Project-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
            400: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimitedError"];
            500: components["responses"]["InternalError"];
        };
    };
    finalizeAudiobookAudioGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current audiobook workflow snapshot after the preview is finalized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalError"];
        };
    };
    getAudiobookWorkflowSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current audiobook workflow snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    approveAudiobookCast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated audiobook workflow snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateAudiobookWorkflowCast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudiobookWorkflowCastUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated audiobook workflow snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    approveAudiobookScript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated audiobook workflow snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateAudiobookWorkflowProductionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudiobookWorkflowProductionSettingsRequest"];
            };
        };
        responses: {
            /** @description Updated audiobook workflow snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiobookWorkflowSnapshotResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
        };
    };
}
